#!/bin/bash

get_duration () {
    output="$(ffprobe -i "$1" -show_format -v quiet)"
    if [[ "$output" =~ duration=([[:graph:]]+) ]]; then
        echo "${BASH_REMATCH[1]}"
    fi
}

if [ -d "$1" ]; then
    find "$1" -type f -name "*.wav" -print0 | 
    while IFS= read -r -d '' file; do get_duration "$file"; done |
    awk '{ sum += $1 } END { print sum }'
elif [ -f "$1" ]; then
    get_duration "$1"
else
    exit 1
fi