#!/usr/bin/env python3

import argparse
import subprocess

from pathlib import Path


parser = argparse.ArgumentParser()
parser.add_argument("file", type=Path)
parser.add_argument("--gpu", action="store_true")
args = parser.parse_args()

if args.file.suffix != ".wav":
    raise ValueError("unsupported format")

demucs_args = [
    "demucs",
    "--two-stems=vocals",
    args.file,
]

if not args.gpu:
    demucs_args[1:1] = ["-d", "cpu"]

subprocess.run(demucs_args, check=True)
